# Use Jupyter's official base image
FROM jupyter/scipy-notebook:latest

# Set working directory inside the container
WORKDIR /home/jovyan

# Set the environment variable to avoid permission errors
ENV JUPYTER_ALLOW_INSECURE_WRITES=1

# Start Jupyter Notebook without authentication
CMD ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]

