version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - './volumen:/home/jovyan'
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_INSECURE_WRITES=1  # Workaround to fix permission issues
    

  api:
    build:
      context: .
      dockerfile: Dockerfile  # Use the existing FastAPI Dockerfile
    container_name: fastapi_server
    ports:
      - "8989:8989"
    volumes:
      - './volumen:/volumen'
    working_dir: /app
    command: uvicorn api:app --host 0.0.0.0 --port 8989 --reload

