version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter  # Use the custom Jupyter Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - './volumen:/home/jovyan'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    user: root  # Run as root initially to fix permissions
    entrypoint: >
      bash -c "chown -R jovyan:users /home/jovyan &&
      chmod -R 700 /home/jovyan/.local/share/jupyter/runtime &&
      chmod -R 755 /home/jovyan &&
      su jovyan -c 'start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --allow-root'"
    

  api:
    build:
      context: .
      dockerfile: Dockerfile  # Use the existing FastAPI Dockerfile
    container_name: fastapi_server
    ports:
      - "8989:8989"
    volumes:
      - './volumen:/volumen'
    working_dir: /app
    command: uvicorn api:app --host 0.0.0.0 --port 8989 --reload

