version: '3'

services:
  ml_service:
    build: ./ML
    ports:
      - "8888:8888"
    volumes:
      - './data:/ml_project/data'
    # Run Jupyter Notebook when the container launches
    command: ["uv","run","jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"] 
    
  api_service:
    build: ./API
    ports:
      - "8989:8989"
    volumes:
      - './data:/api/data'
    # Comando para ejecutar la API con Uvicorn
    command: ["uv","run","uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8989"]
