apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - loadtester-deployment.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-config.yaml
  - grafana-dashboard-api.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

images:
  - name: felaponte/mlops-api
    newTag: v010
  - name: felaponte/mlops-loadtester
    newTag: v010
