apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
        - name: loadtester
          image: felaponte/mlops-loadtester:v2
