apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/felaponte/MLOps2'
    targetRevision: main
    path: 10-CI_CD/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
