name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Detecta push de versiones tipo v1, v2, v3...

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push API image
        run: |
          docker build -t felaponte/mlops-api:${{ env.TAG }} ./10-CI_CD/api
          docker push felaponte/mlops-api:${{ env.TAG }}

      - name: Build and push LoadTester image
        run: |
          docker build -t felaponte/mlops-loadtester:${{ env.TAG }} ./10-CI_CD/loadtester
          docker push felaponte/mlops-loadtester:${{ env.TAG }}

      - name: Update Kustomization tag
        run: |
          sed -i "s/newTag: .*/newTag: ${{ env.TAG }}/" ./10-CI_CD/manifests/kustomization.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./10-CI_CD/manifests/kustomization.yaml
          git commit -m "Update image tags to ${{ env.TAG }}"
          git push
